"""Prometheus metrics collectors and definitions for LuminAI Data Engine.

Exposes metrics for:
  - Records processed count across pipeline stages (clean, deduplicate, validate, stage)
  - Pipeline materialization durations (cleaning, ER, reconciliation)
  - Entity Resolution (ER) match rates, candidate pairs, classifications, and golden records
  - Kafka message consumption and production rates
"""

from __future__ import annotations

import logging
from typing import Any

from prometheus_client import (
    REGISTRY,
    CollectorRegistry,
    Counter,
    Gauge,
    Histogram,
)

logger = logging.getLogger(__name__)


def _get_or_create_metric(collector_cls: type, name: str, documentation: str, labelnames: tuple[str, ...], registry: CollectorRegistry, **kwargs: Any) -> Any:
    """Safely get or register a metric in the registry without throwing AlreadyRegisteredError."""
    try:
        return collector_cls(name, documentation, labelnames=labelnames, registry=registry, **kwargs)
    except ValueError:
        # Already registered in this registry
        return registry._names_to_collectors.get(name) or registry._names_to_collectors.get(f"{name}_total")


# 1. Records Processed Counter
luminai_records_processed_total = _get_or_create_metric(
    Counter,
    "luminai_records_processed_total",
    "Total records processed through data engine pipeline stages.",
    labelnames=("tenant_id", "stage", "status", "entity_type"),
    registry=REGISTRY,
)

# 2. Pipeline Execution Duration Histogram
luminai_pipeline_duration_seconds = _get_or_create_metric(
    Histogram,
    "luminai_pipeline_duration_seconds",
    "Duration of pipeline materialization execution in seconds.",
    labelnames=("pipeline", "status"),
    registry=REGISTRY,
    buckets=(0.1, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0, 120.0, 300.0, float("inf")),
)

# 3. Entity Resolution (ER) Metrics
luminai_er_candidate_pairs_total = _get_or_create_metric(
    Counter,
    "luminai_er_candidate_pairs_total",
    "Total candidate pairs generated by ER blocking.",
    labelnames=("tenant_id",),
    registry=REGISTRY,
)

luminai_er_classifications_total = _get_or_create_metric(
    Counter,
    "luminai_er_classifications_total",
    "Total candidate pair classification decisions (match, review, non_match).",
    labelnames=("tenant_id", "decision"),
    registry=REGISTRY,
)

luminai_er_match_rate = _get_or_create_metric(
    Gauge,
    "luminai_er_match_rate",
    "Entity resolution match rate ratio (matches / total candidate pairs compared).",
    labelnames=("tenant_id",),
    registry=REGISTRY,
)

luminai_er_clusters_total = _get_or_create_metric(
    Counter,
    "luminai_er_clusters_total",
    "Total entity clusters resolved via Union-Find graph clustering.",
    labelnames=("tenant_id",),
    registry=REGISTRY,
)

luminai_er_golden_records_total = _get_or_create_metric(
    Counter,
    "luminai_er_golden_records_total",
    "Total synthesized canonical Golden Records.",
    labelnames=("tenant_id", "entity_type"),
    registry=REGISTRY,
)

# 4. Kafka Message Flow Counters
luminai_kafka_messages_consumed_total = _get_or_create_metric(
    Counter,
    "luminai_kafka_messages_consumed_total",
    "Total Kafka messages consumed from topics.",
    labelnames=("topic", "status"),
    registry=REGISTRY,
)

luminai_kafka_messages_produced_total = _get_or_create_metric(
    Counter,
    "luminai_kafka_messages_produced_total",
    "Total Kafka messages published to topics.",
    labelnames=("topic", "status"),
    registry=REGISTRY,
)


def record_records_processed(
    tenant_id: str,
    stage: str,
    count: int,
    status: str = "success",
    entity_type: str = "Person",
) -> None:
    """Record processed records counter."""
    if count <= 0:
        return
    try:
        luminai_records_processed_total.labels(
            tenant_id=str(tenant_id),
            stage=str(stage),
            status=str(status),
            entity_type=str(entity_type),
        ).inc(count)
    except Exception as exc:
        logger.debug("Failed to update records processed metric: %s", exc)


def record_pipeline_duration(pipeline: str, duration_seconds: float, status: str = "success") -> None:
    """Record pipeline execution duration in seconds."""
    try:
        luminai_pipeline_duration_seconds.labels(
            pipeline=str(pipeline),
            status=str(status),
        ).observe(duration_seconds)
    except Exception as exc:
        logger.debug("Failed to record pipeline duration metric: %s", exc)


def record_er_metrics(
    tenant_id: str,
    candidate_pairs_count: int = 0,
    matches_count: int = 0,
    review_count: int = 0,
    non_matches_count: int = 0,
    clusters_count: int = 0,
    golden_records_count: int = 0,
    entity_type: str = "Person",
) -> None:
    """Record Entity Resolution classification and synthesis metrics."""
    try:
        t_id = str(tenant_id)
        if candidate_pairs_count > 0:
            luminai_er_candidate_pairs_total.labels(tenant_id=t_id).inc(candidate_pairs_count)

        if matches_count > 0:
            luminai_er_classifications_total.labels(tenant_id=t_id, decision="match").inc(matches_count)
        if review_count > 0:
            luminai_er_classifications_total.labels(tenant_id=t_id, decision="review").inc(review_count)
        if non_matches_count > 0:
            luminai_er_classifications_total.labels(tenant_id=t_id, decision="non_match").inc(non_matches_count)

        total_compared = matches_count + review_count + non_matches_count
        if total_compared > 0:
            match_rate = float(matches_count) / float(total_compared)
            luminai_er_match_rate.labels(tenant_id=t_id).set(match_rate)

        if clusters_count > 0:
            luminai_er_clusters_total.labels(tenant_id=t_id).inc(clusters_count)

        if golden_records_count > 0:
            luminai_er_golden_records_total.labels(tenant_id=t_id, entity_type=str(entity_type)).inc(golden_records_count)
    except Exception as exc:
        logger.debug("Failed to record ER metrics: %s", exc)
