apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-data-engine
  labels:
    {{- include "luminai-platform.labels" . | nindent 4 }}
    {{- include "luminai-platform.selectorLabels" "data-engine" | nindent 4 }}
spec:
  type: {{ .Values.dataEngine.service.type }}
  ports:
    - port: {{ .Values.dataEngine.service.port }}
      targetPort: {{ .Values.dataEngine.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "luminai-platform.selectorLabels" "data-engine" | nindent 4 }}